# This is a weird way of telling Travis to use the fast container-based test
# runner instead of the slow VM-based runner.
sudo: false

language: go

env:
  - GO111MODULE=on

go:
  - "1.8"
  - "1.9"
  - "1.10"
  - "1.11"

git:
  depth: false
  submodules: false

install:
  - curl -sSf https://raw.githubusercontent.com/bloom42/rocket/master/install.sh | sh

script:
  - make build
  - make test

deploy:
  provider: script
  skip_cleanup: true # Important, otherwise the build output would be purged.
  script: rocket # use rocket to deploy
  on:
    tags: true # The deployment happens only if the commit has a tag

notifications:
  email:
    on_success: never
