# This is a weird way of telling Travis to use the fast container-based test
# runner instead of the slow VM-based runner.
sudo: false

language: go

env:
  - GO111MODULE=on

go:
  - 1.11

git:
  depth: false
  submodules: false

before_script:
  - go get
  - make test

script:
  - make build
